### PR TITLE
don't want to pass parser here, it doesn't work

### PR DESCRIPTION
**Pull request by ifiddes**
This didn't work with argparse. Now it does.

### CODE REVIEW

**Comment by ifiddes** [comment]
Regardless of the discussion about temp/tmp dirs, this change should probably be merged at some point.  You don't pass in the instance of the parser to its own add_argument_group function. Using argparse instead of optparse for jobTree options does not work without this change.

**Comment by joelarmstrong** [comment]
OK, merged. This still works with optparse, right? If so I'll point progressiveCactus to this version as well.

**Comment by ifiddes** [comment]
Yes, it still works with optparse. The function addOptions is split into
two sections, based on whether a OptionParser or ArgumentParser object was
passed in. It looks like someone wrote in argparse functionality at some
point but didn't test it. Luckily, it seems that everything works with that
one fix.

Ian Fiddes

**Comment by dentearl** [comment]
Ah-hem. I wrote in argparse functionality and tested it and then _someone
else_ (*cough*cough* benedcit) stomped on it in a different update...

**Pull request merged**
