### PR TITLE
Tmp dir location

### PR DESCRIPTION
**Pull request by ifiddes**
This allows for custom locations of tmp dirs for usage on clusters such as npk where each node has its own storage and if you don't use that the main filesystem will be hammered. Also includes the fix that I already made a pull request for that fixes argparse.

### CODE REVIEW

**Comment by diekhans** [comment]
--tempDir whould be --tmpDir, since that how it's spelled on Unix ;-)

While an explicit override is useful, it should use the TMPDIR
environment variable by default.  This should be set on our
clusters.  If it is use TMPDIR, we need to investigate why it's not
set on the cluster.

**Comment by dentearl** [comment]
https://i.imgur.com/c7NJRa2h.jpg

**Comment by diekhans** [comment]
Both spellings? no, that is just adding unnecessary arguments.  Sorry the
unix inventors wanted to save one extra character.  

Both --tmpDir and TMPDIR env, yes, it should be a hierarchy

     --tmpDir overrides TMPDIR, defaults to /tmp

**Comment by ifiddes** [comment]
I have added a commit to fix 'temp' to 'tmp'. 

I don't know who is in charge of npk (behind the cancer firewall), but that cluster does not have $TMPDIR set:

Ians-MacBook-Air:~ ifiddes$ ssh npk
Last login: Tue Jan  6 08:46:05 2015 from 172.30.0.10
Rocks 6.1 (Emerald Boa)
Profile built 20:37 12-Feb-2014

Kickstarted 13:12 12-Feb-2014
-bash-4.1$ echo $TMPDIR

-bash-4.1$ ssh kkr18u56
Last login: Tue Jan  6 08:46:34 2015 from npk.local
Rocks Compute Node
Rocks 6.1 (Emerald Boa)
Profile built 15:22 04-Mar-2014

Kickstarted 15:52 04-Mar-2014
-bash-4.1$ echo $TMPDIR

-bash-4.1$ 

And the attached filesystem (depot4) is NFS. So if I submit a few hundred jobs that all are writing to depot4 it slows to a crawl. Each node has a local 256gb hard drive (/scratch/) but this is not set as $TMPDIR on the node. I don't think it would be straight forward to have each jobTree job set it before proceeding with the job, would it?

**Comment by diekhans** [comment]
Mail cluster-admin@soe.ucsc.edu to request it, you can CC me...

**Comment by dentearl** [comment]
> Both spellings? no, that is just adding unnecessary arguments.

... not sure if srs or trolling >.>

Dent

**Comment by adamnovak** [comment]
It's simple to add extra aliases to argparse options, and might be worth doing.

I'm not sure about the /scratch/tmp default, though, as not everyone necessarily has a /scratch mount.

**Comment by ifiddes** [comment]
R.E. the temp vs tmp debate: when you request a temporary dir from a Target in scriptTree, the method is called getGlobalTempDir()

I agree that setting a default value may be a bad idea.

**Comment by joelarmstrong** [comment]
mktemp (a coreutil) spells it like "temp" as well :) I really don't think it matters.

I think /tmp is the only sane default (if we can't get anything from env variables). It happens to be terrible for our machines because we have , but it's there on every unix system.

I think the common environment variables that people check are TMPDIR, TMP, and TEMP.

PS: should I be merging these pull requests? I have commit access.

**Comment by ifiddes** [comment]
It's not a rush to merge, I got it working on npk by just having cluster admin set the tmpdir variable. When I have a chance I will remove the default setting

Ian Fiddes

**Pull request closed without merging**
